// <auto-generated />
namespace PhoneBook.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class s21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(s21));
        
        string IMigrationMetadata.Id
        {
            get { return "201808280836120_s21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
